version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis: 
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - '3050:80'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules # dont override this folder, because we don't have node modules in local machine
      - ./server:/app
    environment:
      # set on runtime
      - REDIS_HOST=redis # taken from services name
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules # bookmarks node modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev 
      context: ./worker
    volumes:
      - /app/node_modules # bookmarks node modules
      - ./worker:/app

